name: Test Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          echo "Testing new file"
          if [ ! -s <your_file_name> ]; then
            echo "File is empty or missing" && exit 1
          fi
